name: Java CI with Maven

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Download and setup Oracle JDK
        uses: actions/setup-java@v2
        run: |
          wget -q https://download.oracle.com/java/22/latest/jdk-22_linux-x64_bin.tar.gz -O jdk.tar.gz
          tar -xf jdk.tar.gz
          export export JAVA_HOME=$PWD/jdk-22
          export PATH=$JAVA_HOME/bin:$PATH

      - name: Check Java version
        run: java -version

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Start Spring Boot application
        run: java -jar target/demo-0.0.1-SNAPSHOT.jar
