name: Java CI with Maven

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 22
        uses: actions/setup-java@v2
        with:
          java-version: 'adopt@1.22'

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Start Spring Boot application
        run: java -jar target/demo-0.0.1-SNAPSHOT.jar
